use stock;
CREATE TABLE `daily` (
  `stock_id` varchar(16) NOT NULL DEFAULT '',
  `name` varchar(32) DEFAULT NULL,
  `open_price` double DEFAULT NULL,
  `yesterday_close_price` double DEFAULT NULL,
  `current_price` double DEFAULT NULL,
  `highest_price` double DEFAULT NULL,
  `lowest_price` double DEFAULT NULL,
  `buy1_price_` double DEFAULT NULL,
  `sell1_price_` double DEFAULT NULL,
  `deal_total_quantity` bigint(20) DEFAULT NULL,
  `deal_total_money` double DEFAULT NULL,
  `buy1_quantity` bigint(20) DEFAULT NULL,
  `buy1_price` double DEFAULT NULL,
  `buy2_quantity` bigint(20) DEFAULT NULL,
  `buy2_price` double DEFAULT NULL,
  `buy3_quantity` bigint(20) DEFAULT NULL,
  `buy3_price` double DEFAULT NULL,
  `buy4_quantity` bigint(20) DEFAULT NULL,
  `buy4_price` double DEFAULT NULL,
  `buy5_quantity` bigint(20) DEFAULT NULL,
  `buy5_price` double DEFAULT NULL,
  `sell1_quantity` bigint(20) DEFAULT NULL,
  `sell1_price` double DEFAULT NULL,
  `sell2_quantity` bigint(20) DEFAULT NULL,
  `sell2_price` double DEFAULT NULL,
  `sell3_quantity` bigint(20) DEFAULT NULL,
  `sell3_price` double DEFAULT NULL,
  `sell4_quantity` bigint(20) DEFAULT NULL,
  `sell4_price` double DEFAULT NULL,
  `sell5_quantity` bigint(20) DEFAULT NULL,
  `sell5_price` double DEFAULT NULL,
  `date` varchar(10) NOT NULL DEFAULT '',
  `time` varchar(8) NOT NULL DEFAULT '',
  `unknown` varchar(6) DEFAULT NULL,
  PRIMARY KEY (`stock_id`,`date`,`time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
